### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by FutureChen** [PonyGroup/PonyRouter#1]
发现框架里面 所有的Node,都是通过一个block来回调处理事件， 如果用这个框架做项目的路由映射，那么可能存在 几十个或者更多的路由页面，也就是存在大量的block ，这样会不会消耗的内存比较大？

**Comment by PonyCui** [comment]
block 的内存开销可以忽略，不建议在 block 中使用非单例的对象，如果确实要使用非单例对象，务必使用它的weak对象。
如果仍然觉得 block 内存占用太大，可以自行修改成 delegate，这个修改是非常容易做到的。

**Comment by FutureChen** [comment]
嗯，好的，谢谢，非单例对象，让我思考思考
